# Generated by Django 5.2.5 on 2025-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, choices=[('rm', 'Room'), ('as', 'Amenities'), ('dr', 'Dining'), ('ex', 'Exterior')], max_length=2),
        ),
    ]
