# Generated by Django 5.2.5 on 2025-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='size',
            field=models.CharField(choices=[('small', 'Small (col-4)'), ('medium', 'Medium (col-8)'), ('large', 'Large (col-12)')], default='small', max_length=6),
        ),
    ]
