# Generated by Django 5.2.5 on 2025-09-16 17:39

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=gallery.models.get_upload_path),
        ),
    ]
