# Generated by Django 5.2.5 on 2025-09-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, choices=[('room', 'Room'), ('amenities', 'Amenities'), ('dining', 'Dining'), ('exterior', 'Exterior')], max_length=9),
        ),
    ]
