# Generated by Django 5.2.5 on 2025-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, choices=[('rm', 'Room'), ('as', 'Amenities'), ('dr', 'Dining'), ('ex', 'Exterior')], max_length=2),
        ),
    ]
