# Generated by Django 5.2.5 on 2025-09-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('photo', models.ImageField(upload_to='testimonials/photos/', verbose_name='Photo')),
                ('message', models.TextField(verbose_name='Message')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
